version: '3'
services:
  myapp:
    image: myapp-with-prom
    ports:
      - "3000:3000"
    build: .
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
  grafana:
    image: grafana/grafana-oss
    ports:
      - "3001:3000"
